name: Validate Data

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1 # 5
      matrix:
        python-version: ["3.12"] # ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pytest
    #     pip install -r requirements.txt -r requirements-dev.txt

    - name: Lint with Ruff, ignore line length and imports not at top
      run: |
        pip install ruff
        ruff check src --ignore E501,E402

    # - name: Run tests
    #   run: |
    #     pytest

  clab-ci-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        srl-release: ["23.10.3","24.3.2","latest"]
    needs:
    - tests # Will only run if unit tests pass
    steps:
    - uses: actions/checkout@v3

    # TODO ideally this would reuse the work from 'tests'
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        sudo apt install -y snmp

    # - name: pull srlinux image
    #   run: docker pull ghcr.io/nokia/srlinux:latest
    - name: install latest clab
      run: bash -c "$(curl -sL https://get.containerlab.dev)" # -- -v 0.40.0
    - name: start clab ci topo
      run: SR_LINUX_RELEASE=${{ matrix.srl-release }} make deploy-clab-ci
    - name: Wait 3 seconds
      run: sleep 3
    - name: Run all CI tests under test/ci
      run: make run-tests
